### PR TITLE
Transaction IDs, Part II

### PR DESCRIPTION
**Pull request by DFurnes**
### What's this PR do?
Two things I noticed when testing the refactored `ForwardsTransactionIds` trait on Rogue Thor:

🔂 Remove logic to increment a "counter" on request IDs. This doesn't make sense with the format that [Heroku's router](https://devcenter.heroku.com/articles/http-request-id) generates for this header (like `754546b2-a67f-47d1-9eda-203c8f989601` instead of `1515433053.7233-0`), and in hindsight doesn't provide that much value (timestamps should be synced so we can use those to understand order-of-operations).

🈴 If `X-Request-ID` doesn't exist, uses [ramsey/uuid](https://github.com/ramsey/uuid) to generate a new UUID rather than the PHP [`uniqid`](http://php.net/manual/en/function.uniqid.php) built-in, which seems to have significantly less entropy.

🈯️ I renamed `transaction_id` in the generated log to `request_id` for consistency.

### How should this be reviewed?
👀

### Checklist
- [ ] Tests added for new features/bug fixes.
- [ ] Is this a [breaking change](http://semver.org)?

### CODE REVIEW

**Comment by DFurnes** [comment]
Follow-up question – do we think it's even useful for downstream requests to automatically write to the log like this? I'm tempted to think that _just_ forwarding the `X-Request-ID` header is providing the bulk of the value here, and we can more granularly log interesting requests on a case-by-case basis...

**Comment by sbsmith86** [comment]
@DFurnes would other apps then log the forwarded request? I don't think understand where we would actually track request ids if we are not logging them.

**Comment by DFurnes** [comment]
As of DoSomething/rogue#575, we append Request ID to every log message, like so:

```
[2018-01-11 17:08:42] local.INFO: post_created {"id":146,"signup_id":141} {"user_id":"5571f4f5a59dbf3c7a8b4569","request_id":"754546b2-a67f-47d1-9eda-203c8f989601"}
[2018-01-11 18:31:19] testing.INFO: post_reviewed {"id":34,"admin_northstar_id":"5554eac1a59dbf117e8b4567","status":"accepted"} {"user_id":"5554eac1a59dbf117e8b4567","request_id":"ee203fbe-c909-4cb7-8527-22f977be0670"}
[2018-01-11 18:31:20] testing.INFO: post_tagged {"id":35,"tag":"good-photo"} {"user_id":"56d9f70da59dbf176b8b45d2","request_id":"d17028a3-2d16-48e5-a4c0-9d3567cdf89c"}
```

This [code in Gateway](https://github.com/DoSomething/gateway/blob/196508321656b6c11dd5b720d89f4e872f041143/src/ForwardsTransactionIds.php#L28-L35) additional logs _every_ Gateway request made, like requests to Blink or Northstar:

```
[12-Jan-2018 15:04:37 UTC] [2018-01-12 15:04:37] thor.INFO: Request made. {"method":"POST","uri":"https://blink-staging.dosomething.org/api/v1/events/user-signup","transaction_id":"e460cdc8-464a-46d5-9d86-f37ecb5f93a2"} {"user_id":null,"request_id":"e460cdc8-464a-46d5-9d86-f37ecb5f93a2"} 
[12-Jan-2018 15:04:55 UTC] [2018-01-12 15:04:55] thor.INFO: Request made. {"method":"POST","uri":"https://blink-staging.dosomething.org/api/v1/events/user-signup","transaction_id":"e460cdc8-464a-46d5-9d86-f37ecb5f93a2"} {"user_id":null,"request_id":"245f4137-0d9d-478e-af00-65d023293274"} 
[12-Jan-2018 15:19:46 UTC] [2018-01-12 15:19:46] thor.INFO: Request made. {"method":"POST","uri":"https://blink-staging.dosomething.org/api/v1/events/user-signup","transaction_id":"e460cdc8-464a-46d5-9d86-f37ecb5f93a2"} {"user_id":null,"request_id":"f679c325-562a-42da-ab9c-6e3b9707def3"}
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/57900ae6469c64d0168b46a3","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/57aa57fb42a06480308b474b","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/572a7f54469c649a388b4903","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/55be7c24469c64182b91d3e0","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/57213e08469c643c558b4808","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/5695b4a8469c64a8178ccf72","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/56883979469c64a8178ca82f","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} 
[12-Jan-2018 15:36:04 UTC] [2018-01-12 15:36:04] thor.INFO: Request made. {"method":"GET","uri":"https://northstar-thor.dosomething.orgv1/users/id/5693c11b469c64a8178cc67e","transaction_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"} {"user_id":"5543dfd6469c64ec7d8b46b3","request_id":"bd9b1877-892c-4576-bff2-941e61bc50e8"}
```

Since we forward along the `X-Request-ID` header to those services (and so they'll log the incoming request & any app-specific notable events), I'm wondering if also logging the fact that we made that API request here is overkill.

**Comment by DFurnes** [comment]
And either way, not something we need to decide right now! We can always merge this in and then see if we find all the extra log messages distracting or not.

**Comment by sbsmith86** [comment]
Gotcha! Thank you for explaining and If I understand it correctly, I'm not too concerned with the extra log messages right now. I also am in favor of Gateway sort of being the "source of truth" for transactions coming in and out of it so other apps don't have to remember to keep track as much.

**Review by katiecrane — APPROVED** [review]
:person_fencing:

**Review by sbsmith86 — APPROVED** [review]

**Pull request merged**
