### PR TITLE
Improve flow for `Auth::user()`.

### PR DESCRIPTION
**Pull request by DFurnes**
### What's this PR do?
This pull request improves Gateway's server guard so that it can return a `RemoteUser` instance that's filled with details from the JWT token, without having to make a round-trip to the authorization server.

This makes working with Laravel's `Auth::user()` more performant in most cases and allows us to create [policy classes](https://laravel.com/docs/5.5/authorization#writing-policies), which require an actual user instance to exist (see [#153365757](https://www.pivotaltracker.com/story/show/153365757)).

### How should this be reviewed?
This is probably most digestible going commit-by-commit:

💱 I extracted a bunch of methods from `ApiResponse` into a `HasAttributes` trait so that we could also use it in the `RemoteUser` class we make below. f0fafbb

👤 Adds a `RemoteUser` class that either returns details that were embedded in the token (ID, role) or makes a request to Northstar to fetch the rest of the profile. This is then cached for the remainder of the request by the user provider (so multiple calls to `Auth::user()` would still only make one HTTP request). 508adf4, 681b902

◀️ Reverts the little hack I'd made in #97, since we now only make the HTTP call when actually necessary. 508adf4

🏭 Removes an implicit dependency on a `$this->faker` property existing on the `TestCase`. This is true in most (all?) of our apps, but not actually enforced by the package dependencies.

### Checklist
- [ ] Tests added for new features/bug fixes.
- [ ] Is this a [breaking change](http://semver.org)?

### CODE REVIEW

**Comment by DFurnes** [comment]
Just pushing this up before the holidays, still need to add the ability to lazy-load full profile details & make some test helpers so we can easily mock this content in test suites.

❄️ 🎄 ☃️

**Comment by DFurnes** [comment]
This is probably ready for a look! I'll split out test helpers into another PR so this doesn't get bigger.

**Review by sbsmith86 — APPROVED** [review]
looks good to me.

**Comment by DFurnes** [comment]
Thanks @sbsmith86!

**Pull request merged**
